# Generated by Django 5.1.1 on 2024-09-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0003_remove_category_parent_category_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subtitle',
        ),
        migrations.CreateModel(
            name='subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textsub', models.CharField(blank=True, max_length=50, null=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitle', to='app_market.category')),
            ],
        ),
    ]
