# Generated by Django 5.1.1 on 2024-09-26 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0007_blog_detail'),
        ('app_social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_market.product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_useful',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_social.isuseful'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_social.point'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='suggest',
            field=models.BooleanField(null=True),
        ),
    ]
